### PR TITLE
Maven central

### PR DESCRIPTION
**Pull request by nilsfr**
For the Java client for Etherpad to be used it must be published to Maven Central. A description on how to do it is available in the [OSS Repository Hosting Guide](http://central.sonatype.org/pages/ossrh-guide.html).

I have changed the Maven config to enable it to be verisoned, signed and deployed to OSS Repository Hosting. I have not tested it as it requires a project on OSSRH, and this should be created by the owner of the project. [Instructions for Maven](http://central.sonatype.org/pages/apache-maven.html) for how to do this.

I have also renamed the Java package to org.etherpad.client, and the Maven groupId to org.etherpad. Maven Central requires projects to follow a [naming convention](http://central.sonatype.org/pages/choosing-your-coordinates.html). The use of org.etherpad must be approved by the Etherpad project, I guess. If not you can use a DNS domain you control.

I can assist in getting this project into Maven Central, and update it to the latest Etherpad api version after that.

### CODE REVIEW

**Comment by jhollinger** [comment]
Thanks for the PR. Honestly, I no am no longer using this package, hence the near-abandonment. If you'd like I'd be happy to transfer ownership; let me know.

**Comment by nilsfr** [comment]
Sure, I can take over the ownership. I agree it is better to be maintained by someone who uses it.

**Comment by jhollinger** [comment]
Great, I'll transfer it over. Thanks!

**Comment by jhollinger** [comment]
Ah, it won't let me since you have a fork of the same name. If you delete or rename that, should be good.

**Comment by nilsfr** [comment]
I have now renamed my fork.

**Comment by jhollinger** [comment]
Hmm, not it's saying "nilsfr already has a repository in the jhollinger/java-etherpad-lite network." Apparently you have to delete it...

**Comment by nilsfr** [comment]
Den 14. aug. 2015 16:13, skrev Jordan Hollinger:
>
> Hmm, not it's saying "nilsfr already has a repository in the 
> jhollinger/java-etherpad-lite network." Apparently you have to delete 
> it...
>

Done :)

-- 
Nils Fredrik Gjerull
-----------------------------
"Ministry of Eternal Affairs"
Computer Department
( Not an official title :) )

**Pull request merged**
